"""--

Revision ID: 51686198cf10
Revises: b89bc98ea5b6
Create Date: 2026-05-12 18:48:21.445242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51686198cf10'
down_revision = 'b89bc98ea5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        # batch_op.drop_constraint("organizer_id", type_='foreignkey')
        batch_op.drop_column('organizer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['organizer_id'], ['id'])
        batch_op.drop_column('date')

    # ### end Alembic commands ###
