"""Initial migration

Revision ID: ee89c2375091
Revises: 
Create Date: 2026-05-11 18:18:49.031325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee89c2375091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captain_data', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('players_data', sa.String(), nullable=False))
        batch_op.drop_column('data')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('players_data')
        batch_op.drop_column('captain_data')

    # ### end Alembic commands ###
